### ISSUE TITLE
Connector library missing

### ISSUE THREAD

**Issue by BR38** [xgvargas/me-max-kicad#1]
Many thanks for sharing this work.
When I open the schematic file, connector description miss. (MyFootprints:MSTBO-LEFT)
Could you add it to this rep?
BR

**Comment by xgvargas** [comment]
This is an old repository, I kind of forgot about it... I'm using kicad's template system for this now. As soon I have some time I'll upgrade this repo to use my current template. Until that you can use the new files just added on last push.
